export const SUPABASE_URL = "https://fxpsjruggytyillokbdv.supabase.co";
export const SUPABASE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cHNqcnVnZ3l0eWlsbG9rYmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjUzMzQ5NzcsImV4cCI6MjA0MDkxMDk3N30.7LYvPepQ7Bp6IOaEp2ciW-23QLwMWwD0szBdrpewfWo";
